// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALGgBIKrezyLUpP6t_XgGpPy71V-fDeDs',
    appId: '1:786608406748:web:43b54c2093e67ea5e83419',
    messagingSenderId: '786608406748',
    projectId: 'lendr-borrow-share',
    authDomain: 'lendr-borrow-share.firebaseapp.com',
    storageBucket: 'lendr-borrow-share.firebasestorage.app',
    measurementId: 'G-YGN7NCXEXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZnwDGoxTFbaxEC5ah15Tf1lJfnM-H1yw',
    appId: '1:786608406748:android:d2ff3056f3b890b5e83419',
    messagingSenderId: '786608406748',
    projectId: 'lendr-borrow-share',
    storageBucket: 'lendr-borrow-share.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALGgBIKrezyLUpP6t_XgGpPy71V-fDeDs',
    appId: '1:786608406748:web:28ee08a12ca93e36e83419',
    messagingSenderId: '786608406748',
    projectId: 'lendr-borrow-share',
    authDomain: 'lendr-borrow-share.firebaseapp.com',
    storageBucket: 'lendr-borrow-share.firebasestorage.app',
    measurementId: 'G-6VEZ76G833',
  );
}
